micronaut.application.name=fj-middleend-api

datasources.default.url=jdbc:h2:mem:frogjumpdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
datasources.default.username=sa
datasources.default.password=
datasources.default.driver-class-name=org.h2.Driver
datasources.default.dialect=H2

jpa.default.entity-scan.packages=com.acacia.infrastructure.persistence.entity
jpa.default.properties.hibernate.hbm2ddl.auto=create-drop
jpa.default.properties.hibernate.show_sql=true
jpa.default.properties.hibernate.format_sql=true

h2.console.enabled=true
h2.console.path=/h2-console

micronaut.serde.property-naming-strategy=SNAKE_CASE
micronaut.serde.serialization.indent-output=true

jackson.property-naming-strategy=SNAKE_CASE
jackson.serialization.indentation=true